apiVersion: v1
kind: Template

parameters:
  - name: SENDGRID_API_KEY
    required: true
  - name: EMAIL_TO
    required: true
  - name: EMAIL_FROM
    required: true

objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: audit-email-alert
    spec:
      template:
        metadata:
          annotations:
            autoscaling.knative.dev/maxScale: '1'
            autoscaling.knative.dev/target: '1'
            autoscaling.knative.dev/targetUtilizationPercentage: '50'
            autoscaling.knative.dev/window: 30s
          labels:
            app.openshift.io/runtime: quarkus
        spec:
          containers:
            - image: quay.io/evanshortiss/shipwars-email-alerts:latest
              imagePullPolicy: Always
              env:
                - name: SENDGRID_API_KEY
                  value: ${SENDGRID_API_KEY}
                - name: EMAIL_FROM
                  value: ${EMAIL_FROM}
                - name: EMAIL_TO
                  value: ${EMAIL_TO}


