apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: cheat-detector
spec:
 template:
  spec:
   containers:
    - image: image-registry.openshift-image-registry.svc:5000/cloud-services-tmm-stage/shipwars-cheat-detection
      imagePullPolicy: Always
      env:
        - name: JAVA_APP_JAR
          value: "function-1.0.0-SNAPSHOT.jar"
